version = 1

test_patterns = ["unittests/**"]

[[analyzers]]
name = "python"
enabled = true
dependency_file_paths = ["requirements-dev.txt"]

  [analyzers.meta]
  runtime_version = "3.x.x"
  max_line_length = 120
  type_checker = "mypy"
